### ISSUE TITLE
WPT gradient regressions

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1091]
A couple of the gradient reftests are broken with current WR:

```
  ▶ FAIL [expected PASS] /_mozilla/css/border-image-linear-gradient.html
  └   → /_mozilla/css/border-image-linear-gradient.html 9374f4b215c8e79652fcacf5d111ba0a0307ef96
/_mozilla/css/border-image-linear-gradient-ref.html 905bde431c319c7a86a4df9b7543b2a39bd9a22b
Testing 9374f4b215c8e79652fcacf5d111ba0a0307ef96 == 905bde431c319c7a86a4df9b7543b2a39bd9a22b

  ▶ FAIL [expected PASS] /_mozilla/css/linear_gradients_parsing_a.html
  └   → /_mozilla/css/linear_gradients_parsing_a.html d24436d78365996861161375cdad7dcff2c2d5ca
/_mozilla/css/linear_gradients_parsing_ref.html fa3dc596ca9e1f14471de9cb56893e94bd9861b2
Testing d24436d78365996861161375cdad7dcff2c2d5ca == fa3dc596ca9e1f14471de9cb56893e94bd9861b2
```

![rt1](https://cloud.githubusercontent.com/assets/2350882/24841289/9489bbf6-1dc4-11e7-86de-6457182871b1.png)
![rt2](https://cloud.githubusercontent.com/assets/2350882/24841288/948936c2-1dc4-11e7-805d-7300ae5c6297.png)
![rt3](https://cloud.githubusercontent.com/assets/2350882/24841286/94736c84-1dc4-11e7-8661-3d93d0dacbed.png)
![rt4](https://cloud.githubusercontent.com/assets/2350882/24841287/9479c6ec-1dc4-11e7-8736-ec9a6de12cbf.png)

We'll need to get these resolved before we can land a WR update.

cc @kvark @rlhunt

**Comment by rlhunt** [comment]
So one of these failures is resolved with the following patch (from #1078), and the remaining one is a fuzzy match with about 40 pixels off. I will look into the fuzziness problem as soon as I can.
```diff
diff --git a/components/layout/display_list_builder.rs b/components/layout/display_list_builder.rs
index 8c390487f5..091df7e9c8 100644
--- a/components/layout/display_list_builder.rs
+++ b/components/layout/display_list_builder.rs
@@ -952,8 +952,8 @@ impl FragmentDisplayListBuilding for Fragment {
             })
         }
 
-        let center = Point2D::new(absolute_bounds.origin.x + absolute_bounds.size.width / 2,
-                                  absolute_bounds.origin.y + absolute_bounds.size.height / 2);
+        let center = Point2D::new(absolute_bounds.size.width / 2,
+                                  absolute_bounds.size.height / 2);
```

**Comment by glennw** [comment]
It seems like both of these tests are still failing in Servo built against WR master? They fail in different ways to the screenshots above though. Unless there's something special I need to do when updating Servo?

**Comment by glennw** [comment]
Any ideas @rlhunt @kvark ?

![f2](https://cloud.githubusercontent.com/assets/2350882/24885590/ad3601cc-1e92-11e7-8c86-316c1a16fb75.png)
![f1](https://cloud.githubusercontent.com/assets/2350882/24885589/ad2b750e-1e92-11e7-879f-df64019941a0.png)

**Comment by glennw** [comment]
This got fixed!
