### ISSUE TITLE
Transformed images with transformed rectangle clips are not clipped properly

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1732]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401665

\>> [Testcase](https://bug1401665.bmoattachments.org/attachment.cgi?id=8910430) <<

Expected vs actual rendering:
<img width="413" alt="screen shot 2017-09-20 at 3 59 33 pm" src="https://user-images.githubusercontent.com/961291/30664776-d130ff00-9e1c-11e7-91a3-cf86097e6f06.png">

It looks like the image is only clipped to the axis-aligned bounds of the rotated rectangle instead of to the actual rotated rectangle.

In the YAML recording, the `image: "res/1505936895-img-59.png"` item has `"clip-and-scroll": 4`, and the clip with `id: 4` is defined inside the rotated stacking context, so I think this is a webrender bug and not a Gecko bug.

```
---
root: 
  items: 
    -
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 0
      "backface-visible": true
    - 
      bounds: [0, 0, 2880, 1482]
      "clip-rect": [0, 0, 2880, 1482]
      "clip-and-scroll": 0
      "backface-visible": true
      type: rect
      color: white
    - 
      bounds: [0, 0, 2880, 1482]
      "clip-rect": [0, 0, 2880, 1482]
      "clip-and-scroll": 0
      "backface-visible": true
      type: clip
      id: 1
      "content-size": [2880, 1482]
    - 
      "clip-rect": [0, 0, 2880, 1482]
      "clip-and-scroll": 1
      "backface-visible": true
      type: "scroll-frame"
      id: 2
      "content-size": [2880, 1482]
      bounds: [0, 0, 2880, 1482]
    - 
      bounds: [0, 0, 2880, 1482]
      "clip-rect": [0, 0, 2880, 1482]
      "clip-and-scroll": 2
      "backface-visible": true
      type: clip
      id: 3
      "content-size": [2880, 1482]
    - 
      bounds: [0, 0, 2880, 1482]
      "clip-rect": [0, 0, 2880, 1482]
      "clip-and-scroll": 3
      "backface-visible": true
      type: rect
      color: white
    -
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 3
      "backface-visible": true
      type: "stacking-context"
      "scroll-policy": scrollable
      transform: [0.42261827, 0.9063078, 0, 0, -0.9063078, 0.42261827, 0, 0, 0, 0, 1, 0, 267.33633, 66.44954, 0, 1]
      "transform-style": flat
      items: 
        - 
          bounds: [2, 2, 200, 200]
          "clip-rect": [2, 2, 200, 200]
          "clip-and-scroll": 3
          "backface-visible": true
          type: clip
          id: 4
          "content-size": [200, 200]
        - 
          bounds: [2, -182, 152, 216]
          "clip-rect": [2, 0, 152, 34]
          "clip-and-scroll": 4
          "backface-visible": true
          image: "res/1505936895-img-59.png"
          "stretch-size": [152, 216]
          "tile-spacing": [0, 0]
        - 
          bounds: [0, 0, 204, 204]
          "clip-rect": [0, 0, 204, 204]
          "clip-and-scroll": 3
          "backface-visible": true
          type: border
          width: 2
          "border-type": normal
          color: 0 0 255 1.0000
          style: solid
    - 
      bounds: [0, 0, 0, 0]
      "clip-rect": [0, 0, 0, 0]
      "clip-and-scroll": 0
      "backface-visible": true
  id: [1, 1]
pipelines: []
```

**Comment by glennw** [comment]
Fixed in #1760

**Comment by TerraX-net** [comment]
This wasn't completely fixed.
The thin grey line inside the blue square is still there although it shouldn't.

**Comment by mstange** [comment]
Let's track the thin line in a different bug.

**Comment by kvark** [comment]
Alright, moving to #1797
