### ISSUE TITLE
box-shadows on large areas cause rendering glitches

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1922]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411131

[Testcase](https://bug1411131.bmoattachments.org/attachment.cgi?id=8921557)

This testcase looks very odd in WebRender Firefox on my machine. It triggers glitches in the UI, it displays incorrectly, and sometimes it flickers, alternating between different renderings on each frame.

I'm guessing that some cache is being exhausted, or maybe cache parts for other things are being overwritten by the shadow.

<img width="1438" alt="screen shot 2017-10-24 at 1 39 41 pm" src="https://user-images.githubusercontent.com/961291/31958798-df20b4b6-b8c0-11e7-9b77-90b425d4f66e.png">

**Comment by Darkspirit** [comment]
(In this testcase I have to zoom in to 120% to see this issue. I hadn't to do that on my example website.)

**Comment by Darkspirit** [comment]
@mstange I can no longer reproduce this bug since the latest webrender update. Can you confirm this?

Commits between the previous and latest webrender update:
https://github.com/servo/webrender/compare/4b8493d6bdc64d2d83202ac15b06b0d4b14c6e76...c0194de78ce26106a8497484dc8d159069e3a482

**Comment by mstange** [comment]
I can no longer reproduce this either. It was most likely fixed by #1954.

However, I don't think the underlying bug has been debugged as part of that fix. So I'm worried that we might still hit similar glitches in other scenarios where we try to allocate extremely large alpha render target pieces. @glennw, should we leave this open so that the glitches can be debugged? Or should we resolve this since this particular testcase no longer triggers the glitches?

**Comment by glennw** [comment]
@mstange I agree that it's likely the underlying bug still exists. I think we can resolve this now though since it's not really actionable with this test case. We can open a new bug when a repro is found, or just re-open this one with further information. Thanks!
