### ISSUE TITLE
WebRender doesn't respect ClearType parameters

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [servo/webrender#2407]
Test case:
data:text/html,abcdefghijklmnopqrstuvwxyz

ClearType enabled, Gamma: 2.2 Pixel Structure: BGR ClearType Level: 0 Enhanced Contrast: 0
WebRender off: https://i.imgur.com/bV4HjfK.png
WebRender on: https://i.imgur.com/V3xJ5IN.png

ClearType enabled, Gamma: 2.2 Pixel Structure: RGB ClearType Level: 100 Enhanced Contrast: 400
WebRender off: https://i.imgur.com/zYKWHE0.png
WebRender on: https://i.imgur.com/boU7srJ.png

As can be seen, WebRender gives exactly the same output in both cases.

OS: Windows 10
GPU: Nvidia GeForce GTX 970
Browser: Nightly 60.0a1 (2018-02-11) (64-bit)

**Comment by glennw** [comment]
cc @lsalzman

**Comment by kvark** [comment]
Please note that you can drop the images right into Github issue/comment area, showing them inline:

| off | on |
| --- | ---  |
| ![off](https://i.imgur.com/bV4HjfK.png) | ![on](https://i.imgur.com/V3xJ5IN.png) |
| ![off](https://i.imgur.com/zYKWHE0.png) | ![on](https://i.imgur.com/boU7srJ.png) |

**Comment by Gankro** [comment]
possibly related: on windows, a google spread sheet with `arial` text has terrible kerning right now

**Comment by Gankro** [comment]
false alarm: that is a bug even vanilla gecko has right now

**Comment by Gankro** [comment]
test

**Comment by mstange** [comment]
@automatedbugreportingfacility is this fixed now? #2896 might have fixed it.

**Comment by gw3583** [comment]
I believe this is fixed - @automatedbugreportingfacility could you confirm?

**Comment by automatedbugreportingfacility** [comment]
This is definitely very close to the expected result after the fixes. However, for some reason, I'm still not getting pixel-to-pixel match for WebRender on/off in this basic case:

URL: data:text/html,abcdefghijklmnopqrstuvwxyz
ClearType Parameters: Gamma: 2.2 Pixel Structure: BGR ClearType Level: 0 Enhanced Contrast: 0

| WebRender off | WebRender on | 
| --- | --- |
| ![22-bgr-0-0-nowr](https://user-images.githubusercontent.com/3524640/45107868-409cba00-b13b-11e8-9ea3-8b75fe0c4020.png) | ![22-bgr-0-0-wr](https://user-images.githubusercontent.com/3524640/45107925-6c1fa480-b13b-11e8-902c-a679e8cf0f80.png) |

I'm not sure if this is expected or not. At the very least, there must be some difference.

Attempting to dig a little deeper, I've devised the following testcase:
URL: `data:text/html,<div style="font-size:5000">a</div><script>scrollTo(0,875)</script>`
ClearType Parameters: Gamma: 2.2 Pixel Structure: BGR ClearType Level: 0 Enhanced Contrast: 0

| WebRender off | WebRender on |
| --- | --- |
| ![a-22-bgr-0-0-nowr](https://user-images.githubusercontent.com/3524640/45108281-7aba8b80-b13c-11e8-8e6c-a8e1b7f05d34.png) | ![a-22-bgr-0-0-wr](https://user-images.githubusercontent.com/3524640/45108293-81490300-b13c-11e8-9a78-bb5efd7c4655.png) |

As can be seen, edges of the character are significantly more blurred in the WebRender case.

**Comment by mstange** [comment]
> However, for some reason, I'm still not getting pixel-to-pixel match for WebRender on/off in this basic case:
> URL: data:text/html,abcdefghijklmnopqrstuvwxyz
> I'm not sure if this is expected or not. At the very least, there must be some difference.

That's an interesting case. The font rendering inside the URL bar looks identical to my eyes, but I didn't check the pixel values. What's interesting though are the differences in the tab text and in the content. WebRender doesn't use subpixel AA in the tabs yet (that's tracked by [bug 1455393](https://bugzilla.mozilla.org/show_bug.cgi?id=1455393)), so the tab text difference is expected. However, it looks like non-WebRender doesn't use subpixel AA in the tab content on your machine! That's really unexpected.

> As can be seen, edges of the character are significantly more blurred in the WebRender case.

This is also interesting but it's probably a separate bug that only affects very large font sizes.

**Comment by Gankro** [comment]
In the very large case I expect you're running into webrender's current upper-bound on glyph-size, where it starts to render at a smaller size and just upscale. A known, separate issue.

**Comment by lsalzman** [comment]
Yes, that's just a case of hitting the font size limit. Since we don't use path rasterization above the limit like Skia does, the results won't be the same if you use an absurdly large font size like in that example.

**Comment by mstange** [comment]
All right, then I recommend closing this issue.

**Comment by automatedbugreportingfacility** [comment]
> However, it looks like non-WebRender doesn't use subpixel AA in the tab content on your machine! That's really unexpected.

I can investigate this further, if needed. The setup is pretty regular: the latest Nightly, GeForce GTX 970 running with the latest drivers (8-21-2018). From what I gathered, I can verify that subpixel AA is used or not by zooming into the screenshot and seeing if characters are slightly colored?

**Comment by lsalzman** [comment]
Subpixel AA is disabled at huge sizes where the font is scaled up, since the entire idea of subpixels thus breaks down. It's expected.

**Comment by mstange** [comment]
> From what I gathered, I can verify that subpixel AA is used or not by zooming into the screenshot and seeing if characters are slightly colored?

That's right. Your test page is the simplest page imaginable, so I'd be surprised if more complicated pages used subpixel AA when this page is not... in any case, this is not a WebRender bug, so if you'd like to investigate this further, please file a bug on bugzilla.mozilla.org in the Graphics: Layers component and we can discuss there.

@lsalzman the non-WebRender broken case is the one with the regular font size

**Comment by automatedbugreportingfacility** [comment]
Okay, thank you for the comments and fixes.
