### ISSUE TITLE
Webrender CI intermittently fails

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#3248]
The macOS debug build is intermittently failing in webrender CI. All the failures appear to be on the wr-toronto-1 worker, and always fail on the `rand` crate compilation. I looked at a few good vs bad logs, and in the good cases the command that's run is this:

```
sccache rustc --crate-name rand /Users/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="libc"' --cfg 'feature="std"' -C metadata=036fd69d32b51127 -C extra-filename=-036fd69d32b51127 --out-dir /Users/worker/generic-worker/generic-worker-taskdir/task_1540896746/webrender/target/debug/deps -L dependency=/Users/worker/generic-worker/generic-worker-taskdir/task_1540896746/webrender/target/debug/deps --extern libc=/Users/worker/generic-worker/generic-worker-taskdir/task_1540896746/webrender/target/debug/deps/liblibc-3a24e28cdb54211e.rlib --cap-lints allow --deny warnings
```

and in the bad case it's this:

```
sccache rustc --crate-name rand /Users/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="libc"' --cfg 'feature="std"' -C metadata=4885fbb33c82b8cc -C extra-filename=-4885fbb33c82b8cc --out-dir /Users/worker/generic-worker/generic-worker-taskdir/task_1540884279/webrender/target/debug/deps -L dependency=/Users/worker/generic-worker/generic-worker-taskdir/task_1540884279/webrender/target/debug/deps --cap-lints allow --deny warnings
```

Notably, the bad case is missing the `--extern libc=...` bit. I don't yet know why this only happens intermittently and only on wr-toronto-1.

**Comment by staktrace** [comment]
For reference you can find logs by going to https://tools.taskcluster.net/provisioners/localprovisioner/worker-types/webrender-ci-osx/workers/wr-toronto/wr-toronto-1 and clicking on the job name.

**Comment by staktrace** [comment]
In the bad case cargo apparently doesn't realize libc is a dependency of rand, and tries to compile rand without compiling libc first. I strongly suspect this is an sccache bug.

/cc @luser

**Comment by luser** [comment]
I wouldn't rule it out entirely, but sccache doesn't generate those compiler commandlines, cargo does. It's possible that somehow the output that sccache produces causes cargo to do the wrong thing, but IIRC the list of externs is determined up-front before any compilation happens.

**Comment by alexcrichton** [comment]
Oh dear this looks pretty bad! This is oddly something I've never seen before so I wouldn't really know where to start looking. I agree with @luser though that it really does sort of look like Cargo is just forgetting a dependency. I'm not sure how that would happen, though, when it's worked reliably everywhere else for so long...

**Comment by staktrace** [comment]
@alexcrichton is there any additional logging I can turn on to help diagnose?

**Comment by alexcrichton** [comment]
@staktrace you could try a pretty verbose version of `RUST_LOG=cargo=trace` although that may produce tons of output and slow things down a lot. If a failure can be captured with that though it may help to at least sanity check what Cargo's doing internally

**Comment by alexcrichton** [comment]
Oh jeez that's a bummer... 

Is there perhaps a persistent cargo home between runs? Maybe something got accidentally corrupted there?

**Comment by staktrace** [comment]
There is a persistent cargo home, but I would expect corruption there to show up consistently on every run (or not at all). I don't see why it would be intermittent...

**Comment by alexcrichton** [comment]
Ah sorry the I'm out of ideas for what could be happening :(

**Comment by staktrace** [comment]
Ok. @luser the same machine was also hitting a different error:

```
error: Connection to server timed out
error: Could not compile `osmesa-src`.
```

see e.g. https://tools.taskcluster.net/groups/Pn4pQoxCSbmTQpadRq0svQ/tasks/SEwFsKYqTRGCFKT02nMeWg/runs/0/logs/public%2Flogs%2Flive_backing.log#L1246 

Does this one look more like an sccache error?

At any rate, I've quarantined this worker for now so that it doesn't pick up tasks. Having one good CI machine instead of one good one and one flaky one means we'll go slower but won't have to keep manually retriggering.

**Comment by staktrace** [comment]
@luser Here's one where the sccache server failed to start:

https://tools.taskcluster.net/groups/DTMD8-1sTBexU-C96R9S5Q/tasks/L43E00V3T9qP4ywvwCjzcw/runs/0

Log seems to indicate the command line was parsed and then... nothing?

**Comment by gw3583** [comment]
I think this is resolved now? Please reopen if still relevant.

**Comment by staktrace** [comment]
Might still happen but we disabled sccache and it's not really relevant anymore since we only do a handful of CI runs on GitHub now.
